# Generated by Django 4.1.11 on 2023-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0003_facultyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
