# Generated by Django 4.1.11 on 2023-09-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0006_lectureeventfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyEventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_text', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sirapp.facultyevent')),
            ],
        ),
    ]
