# Generated by Django 4.1.11 on 2023-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0010_participanttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('program_type', models.CharField(max_length=100)),
                ('program_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('program_duration', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('terms_and_conditions', models.BooleanField()),
                ('participants_type', models.ManyToManyField(blank=True, to='sirapp.participanttype')),
            ],
        ),
    ]
