# Generated by Django 4.1.11 on 2023-09-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0011_requestformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_picker', models.DateField()),
                ('program_type', models.CharField(choices=[('Guest Lecture', 'Guest Lecture'), ('Faculty Development Program', 'Faculty Development Program'), ('Student Development Program', 'Student Development Program')], max_length=100)),
                ('program_topic', models.CharField(max_length=255)),
                ('program_duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(choices=[('B Tech', 'B Tech'), ('B Pharmacy', 'B Pharmacy'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('B Com', 'B Com'), ('BA', 'BA'), ('B Sc', 'B Sc')], max_length=100)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=100)),
                ('semester', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_participant', models.ManyToManyField(to='sirapp.typeofparticipant')),
            ],
        ),
    ]
